// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-label'
  | 'menupopup-label'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'zoteroagy-item-section-agy-head-text'
  | 'zoteroagy-item-section-agy-sidenav-tooltip';
