// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "cliPath": string;
      "model": string;
      "language": string;
      "autoContext": boolean;
      "saveHistory": boolean;
      "maxHistoryLength": number;
      "theme": string;
      "fontSize": number;
      "conversations": string;
      "customTemplates": string;
      "keepWindowTop": boolean;
    };
  }
}
